# Default initial positions for mobiarm's ros2_control fake system

initial_positions:
  gripperfinger_left_joint: 0
  gripperfinger_right_joint: 0
  j1_waist: 0
  j2_shoulder: 0
  j3_elbow: 0
  j4_wrist: 0
  j5_wrist: 0
  j6_wrist: 0