# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - j1_waist
      - j2_shoulder
      - j3_elbow
      - j4_wrist
      - j5_wrist
      - j6_wrist
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripperfinger_left_joint
      - gripperfinger_right_joint